# use config for global blog settings.
# frequently changed settings go in data.
# if you change _config.yml, make sure to restart the server process.

# SITE SETTINGS
# access in templates via {{ site.myvariable }}
author: Alek Sharma
title: Alek Sharma
email: aleksharma12@gmail.com
description: Providing optimistic dissonance for the busy human since 1989.
url: "http://aleksharma.com"
twitter_username: alek_sharma
github_username: smart-alek

# BUILD SETTINGS
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  poems:
    output: true
  short-stories:
    output: true
